FROM python: 3.13

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CSM ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]